# Generated by Django 4.2.6 on 2023-10-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='dataTime',
            new_name='dateTime',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
